<?php
/**
 * StationsPodcastsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  AzuraCast
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AzuraCast
 *
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 *
 * The version of the OpenAPI document: 0.20.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace AzuraCast\Test\Api;

use \AzuraCast\Configuration;
use \AzuraCast\ApiException;
use \AzuraCast\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * StationsPodcastsApiTest Class Doc Comment
 *
 * @category Class
 * @package  AzuraCast
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StationsPodcastsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addEpisode
     *
     * .
     *
     */
    public function testAddEpisode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addPodcast
     *
     * .
     *
     */
    public function testAddPodcast()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEpisode
     *
     * .
     *
     */
    public function testDeleteEpisode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePodcast
     *
     * .
     *
     */
    public function testDeletePodcast()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePodcastArt
     *
     * .
     *
     */
    public function testDeletePodcastArt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePodcastEpisodeArt
     *
     * .
     *
     */
    public function testDeletePodcastEpisodeArt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePodcastEpisodeMedia
     *
     * .
     *
     */
    public function testDeletePodcastEpisodeMedia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editEpisode
     *
     * .
     *
     */
    public function testEditEpisode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editPodcast
     *
     * .
     *
     */
    public function testEditPodcast()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEpisode
     *
     * .
     *
     */
    public function testGetEpisode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEpisodes
     *
     * .
     *
     */
    public function testGetEpisodes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPodcast
     *
     * .
     *
     */
    public function testGetPodcast()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPodcastArt
     *
     * .
     *
     */
    public function testGetPodcastArt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPodcastEpisodeArt
     *
     * .
     *
     */
    public function testGetPodcastEpisodeArt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPodcastEpisodeMedia
     *
     * .
     *
     */
    public function testGetPodcastEpisodeMedia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPodcasts
     *
     * .
     *
     */
    public function testGetPodcasts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postPodcastArt
     *
     * .
     *
     */
    public function testPostPodcastArt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postPodcastEpisodeArt
     *
     * .
     *
     */
    public function testPostPodcastEpisodeArt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postPodcastEpisodeMedia
     *
     * .
     *
     */
    public function testPostPodcastEpisodeMedia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
